feat: add streams param on createProject and updateProject, update test cases
streamr-dev/network-contracts pull request #448
Opened 2023-02-01 15:46 UTC by samigabor

2023-02-07 07:57 UTC, jtakalai requested changes

2023-02-07 07:57 UTC, jtakalai commented on packages/hub-contracts/contracts/ProjectRegistry/ProjectRegistry.sol
> +        }
This seems wasteful, on several levels:
* removing all streams should be more like
```
uint streamCount = p.streams.length;
for (uint256 i = 0; i < streamCount; i++) {
    p.streams.pop();
}
```
* does that even work? Doesn't p.streams.length become less when streams are removed?
* `StreamRemoved` then `StreamAdded` are emitted for streams with no change
* we should have O(1) lookup of "hasStream" (instead of the `isStreamAdded` function)
* use that lookup to only add streams to be added, then delete streams to be deleted (or even replace to avoid moving during deletion!), emit proper events only when streams are actually added/removed

2023-02-07 07:57 UTC, jtakalai commented on packages/hub-contracts/contracts/ProjectRegistry/ProjectRegistry.sol
> +                streams[i] = streams[streams.length - 1];
good catch! Wonder how this worked before :D

Did you add test to see the previous implementation was broken?

2023-02-08 09:07 UTC, samigabor commented on packages/hub-contracts/contracts/ProjectRegistry/ProjectRegistry.sol
> +        }
refactored & fixed the streams length issue

2023-02-08 09:08 UTC, samigabor commented on packages/hub-contracts/contracts/ProjectRegistry/ProjectRegistry.sol
> +                streams[i] = streams[streams.length - 1];
yes, and the previous test cases didn't cover removing  multiple streams at once

2023-02-08 12:02 UTC, jtakalai approved these changes

2023-02-08 14:50 UTC, merged