Pick reviewers from outside the bounty first
streamr-dev/network-contracts pull request #468
Opened 2023-02-21 18:25 UTC by jtakalai

2023-02-22 19:06 UTC, jtakalai commented on packages/network-contracts/test/hardhat/BrokerEconomics/BountyPolicies/VoteKickPolicy.test.ts
> +            expect(reviewers.slice(0, 4)).to.have.members([brokers[4].address, brokers[5].address, brokers[6].address, brokers[7].address])
here's the gist of this commit: test

2023-02-22 19:07 UTC, jtakalai commented on packages/network-contracts/contracts/BrokerEconomics/BountyPolicies/VoteKickPolicy.sol
> +        }
here's the gist of this commit: feature code

2023-02-23 05:48 UTC, samt1803 approved these changes
looks good

2023-02-23 06:27 UTC, samt1803 requested changes
there seems to be an issue with the logic we should go through some tests first

2023-02-24 11:02 UTC, samt1803 approved these changes

2023-02-24 11:07 UTC, merged