ETH-401 Consolidate all subgraphs into one
streamr-dev/network-contracts pull request #497
Opened 2023-03-23 20:53 UTC by samigabor

2023-03-27 09:32 UTC, jtakalai requested changes

2023-03-27 20:31 UTC, samigabor commented on packages/network-subgraphs/README.md
> +Project example queries:
updated examples

2023-03-28 06:53 UTC, jtakalai approved these changes
good changes to examples 👍

2023-03-28 09:07 UTC, samigabor commented on packages/network-subgraphs/package.json
> +    "docker:build": "npm run codegen && npm run graphbuild && docker build . -t streamr/graph-deploy-streamregistry-subgraph:dev",
Updated readme as well

2023-03-28 10:04 UTC, merged