Eth 486 project staking subgraph changes
streamr-dev/network-contracts pull request #511
Opened 2023-04-03 10:03 UTC by samigabor

2023-04-06 07:48 UTC, jtakalai requested changes
👍

2023-04-06 07:48 UTC, jtakalai commented on packages/docker-dev-chain-init/projectsData.json
> +        "metadata": "{\"isDataUnion\": true}, \"description\": \"payable with DATA\"}"
👍

2023-04-06 07:48 UTC, jtakalai commented on packages/network-subgraphs/tests/helpers/mocked-entity.ts
> +// artemisie + ambrozie iau tratament pe final de iulie (20-25 iulie)
clean up comments :)

2023-04-06 07:48 UTC, jtakalai commented on packages/network-subgraphs/schema.graphql
> +type ProjectStakeByUser @entity {
I guess the question here is, should we have these derived fields now in User and Project so that you could travel from Project into ProjectStakeByUser (e.g. "give me all users staked into projects that this user has staked to"), because now it's just from ProjectStakeByUser into User and Project, if I understand correctly? You can START from ProjectStakeByUser by only selecting those with a specific user or project, so it probably covers most cases like this, too. Just thinking if adding that derived field to User and Project "costs" anything?

2023-04-11 13:24 UTC, samigabor commented on packages/network-subgraphs/schema.graphql
> +type ProjectStakeByUser @entity {
not needed at this point, but can be added later

2023-04-17 07:11 UTC, jtakalai commented on packages/hub-contracts/test/contracts/ProjectStakingV1.test.ts
> +                .withArgs(projectId1, staker1.address, unstakingAmount, projectStakeBefore.sub(unstakingAmount))
hum so... was the final verdict that we keep these extra arguments or not?

2023-04-17 10:38 UTC, jtakalai commented on packages/hub-contracts/test/contracts/ProjectStakingV1.test.ts
> +                .withArgs(projectId1, staker1.address, unstakingAmount, projectStakeBefore.sub(unstakingAmount))
ok so we keep them in contract (not roll back contracts) but the new event needs to be supported in the old hub-subgraph

2023-04-17 10:38 UTC, jtakalai approved these changes
👍

2023-04-17 10:39 UTC, merged