BrokerPool features for miner fleet load balancing
streamr-dev/network-contracts pull request #519
Opened 2023-04-11 10:24 UTC by samigabor

- add metadata field and setter for broker pool
- create stream at pool creation time
- grant/revoke stream permissions when adding/removing a node

2023-04-19 09:01 UTC, jtakalai requested changes
naming changes requested, that reflect the upcoming ETH-498 naming

2023-04-19 09:01 UTC, jtakalai commented on packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
> +    function updatePoolMetadata(string calldata metadataJsonString) external onlyBroker {
remove word "pool"

2023-04-19 09:01 UTC, jtakalai commented on packages/network-contracts/test/hardhat/BrokerEconomics/deployBrokerPool.ts
> +    poolMetadata = "",
operatorMetadata

2023-04-19 10:19 UTC, samt1803 commented on packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
> +interface IStreamRegistry {
please remove interface and import StreamRegistryV4

2023-04-19 10:23 UTC, samt1803 commented on packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
> +        metadata = poolParams[1];
use setter here so the event is also fired or just fire event here

2023-04-19 10:26 UTC, samt1803 commented on packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
> +        streamRegistry.createStream(streamPath, "metadata");
maybe {} instead of metadata

2023-04-19 10:40 UTC, samt1803 commented on packages/network-contracts/test/hardhat/BrokerEconomics/deployTestContracts.ts
> +
move to deployTestcontracts method

2023-04-19 20:01 UTC, samigabor commented on packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
> +        streamPath = "/broker/coordination";
updated

2023-04-19 20:02 UTC, samigabor commented on packages/network-contracts/test/hardhat/BrokerEconomics/deployBrokerPool.ts
> +    poolMetadata = "",
changed

2023-04-19 20:07 UTC, samigabor commented on packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
> +interface IStreamRegistry {
StreamRegistry contract uses solidity `0.8.9` and the brokerPool has `^0.8.13` and the compiler doesn't allow such import, so I changed this contract pragma from `^0.8.13` to `>=0.8.9 <0.9.0`

2023-04-19 20:09 UTC, samigabor commented on packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
> +        metadata = poolParams[1];
emitted the event

2023-04-19 20:09 UTC, samigabor commented on packages/network-contracts/contracts/BrokerEconomics/BrokerPool.sol
> +        streamRegistry.createStream(streamPath, "metadata");
changed

2023-04-19 20:09 UTC, samigabor commented on packages/network-contracts/test/hardhat/BrokerEconomics/deployTestContracts.ts
> +
moved

2023-04-20 06:53 UTC, jtakalai approved these changes

2023-04-20 06:53 UTC, merged