Eth 535 pull earnings into operator contract
streamr-dev/network-contracts pull request #571
Opened 2023-06-28 15:50 UTC by samigabor

2023-06-30 11:20 UTC, samt1803 requested changes
also change punish test to use operators share

2023-06-30 11:20 UTC, samt1803 commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +        if (sumEarnings > allowedDifference) {
deduct brokers share here, also add a test, that test edge case values

2023-07-03 08:13 UTC, samigabor commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +        if (sumEarnings > allowedDifference) {
Updated

2023-07-03 14:43 UTC, jtakalai approved these changes
👍

2023-07-03 14:43 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +        emit PoolValueUpdate(totalValueInSponsorshipsWei, token.balanceOf(address(this)));
event was missing? Good catch 👍

2023-07-04 12:32 UTC, jtakalai requested changes

2023-07-04 12:32 UTC, jtakalai commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
> +            // TODO
Add test

2023-07-04 20:38 UTC, samigabor commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
> +            // TODO
Added

2023-07-05 13:13 UTC, jtakalai requested changes
👍

2023-07-05 13:13 UTC, jtakalai commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
> +            await operator.withdrawEarningsFromSponsorships([sponsorship.address])
wrap with `.wait()`

2023-07-05 13:13 UTC, jtakalai commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
> +            await operator.connect(delegator).undelegate(parseEther("100"))
wrap with `.wait()`

2023-07-05 14:00 UTC, merged