ETH-574: Move minimumStakeWei to StreamrConfig
streamr-dev/network-contracts pull request #607
Opened 2023-08-19 10:36 UTC by jtakalai

2023-08-21 07:07 UTC, samt1803 requested changes

2023-08-21 07:07 UTC, samt1803 commented on packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/StakeWeightedAllocationPolicy.test.ts
> +
TODO here with mystery behaviour?

2023-08-21 07:07 UTC, samt1803 commented on packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/MaxOperatorsJoinPolicy.test.ts
> +        const sponsorship = await deploySponsorshipWithoutFactory(contracts, { maxOperatorCount: 2 }) // TODO: why 2 and not 1?
TODO here with mystery behaviour

2023-08-21 07:07 UTC, samt1803 commented on packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/StakeWeightedAllocationPolicy.test.ts
> +        expect(formatEther(newTokens1)).to.equal("3000.0")
before the test did the calculation of the expected values from the the initial values, now it is just magic numbers. Why this change?

2023-08-21 07:07 UTC, samt1803 commented on packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/StakeWeightedAllocationPolicy.test.ts
> +        await (await sponsorship.sponsor(parseEther("20000"))).wait()
why did this change from some 'crooked' number to something 'even'?

2023-08-21 07:21 UTC, jtakalai commented on packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/StakeWeightedAllocationPolicy.test.ts
> +
there's a ticket for it

2023-08-21 07:24 UTC, jtakalai commented on packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/MaxOperatorsJoinPolicy.test.ts
> +        const sponsorship = await deploySponsorshipWithoutFactory(contracts, { maxOperatorCount: 2 }) // TODO: why 2 and not 1?
also in the ticket

2023-08-21 07:25 UTC, jtakalai commented on packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/StakeWeightedAllocationPolicy.test.ts
> +        await (await sponsorship.sponsor(parseEther("20000"))).wait()
no idea why it was crooked

2023-08-22 07:54 UTC, jtakalai commented on packages/network-contracts/test/hardhat/OperatorTokenomics/SponsorshipPolicies/MaxOperatorsJoinPolicy.test.ts
> +        const sponsorship = await deploySponsorshipWithoutFactory(contracts, { maxOperatorCount: 2 }) // TODO: why 2 and not 1?
fixed, the fix was in fact easy -___-

2023-08-22 10:23 UTC, samt1803 approved these changes
looks good!

2023-08-22 12:09 UTC, merged