Eth 564 update operators cut fraction
streamr-dev/network-contracts pull request #618
Opened 2023-08-30 06:26 UTC by samigabor

https://linear.app/streamr/issue/ETH-564/add-operatorsetoperatorscutfraction

2023-09-01 09:31 UTC, jtakalai requested changes
👍

2023-09-01 09:31 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +    mapping(Sponsorship => uint) public slashedInto;
into -> in

2023-09-01 09:31 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +    uint public totalStakeInSponsorshipsWei;
this is actually now `totalStakedIntoSponsorshipsWei`

2023-09-01 09:31 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +    uint public slashedInSponsorshipsWei;
move this up next to the totalStaked...

2023-09-01 09:31 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +    uint public slashedInSponsorshipsWei;
call it totalSlashedInSponsorshipsWei

2023-09-01 09:31 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +        emit PoolValueUpdate(totalStakeInSponsorshipsWei, token.balanceOf(address(this)));
For every PoolValueUpdate: send out `totalStakedIntoSponsorshipsWei - totalSlashedInSponsorshipsWei` because that's the totalStakeInSponsorshipsWei (staked - slashed)

2023-09-01 09:31 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +        slashedInto[sponsorship] = 0;
move down to where others are zeroed

2023-09-01 09:31 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +        emit PoolValueUpdate(totalStakeInSponsorshipsWei, token.balanceOf(address(this)));
add `StakeUpdate` since the stake changed.

Also go through every other StakeUpdate and use
```
emit StakeUpdate(sponsorship, stakedInto - slashedIn);
```
instead of 
```
emit StakeUpdate(sponsorship, sponsorship.stakedWei(address(this)));
```

2023-09-01 11:54 UTC, samigabor commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +    mapping(Sponsorship => uint) public slashedInto;
Renamed

2023-09-01 11:59 UTC, samigabor commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +    uint public totalStakeInSponsorshipsWei;
Renamed

2023-09-01 12:00 UTC, samigabor commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +    uint public slashedInSponsorshipsWei;
Moved and renamed

2023-09-01 12:00 UTC, samigabor commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +        slashedInto[sponsorship] = 0;
Moved

2023-09-04 10:53 UTC, jtakalai approved these changes

2023-09-04 10:59 UTC, merged