feat: make slashing fraction configurable
streamr-dev/network-contracts pull request #624
Opened 2023-09-07 20:48 UTC by samigabor

Add slashingFraction to StreamrConfig
Change math for setting the flag stake
Update commnens in contracts and tests

2023-09-08 12:54 UTC, jtakalai approved these changes

2023-09-08 12:54 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.sol
> +        // TODO: after taking at least minimumStake, all "1 - slashingFraction" here are probably overthinking
I think you can just remove this TODO and simplify the below check

2023-09-08 12:54 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.sol
> +        require(committedStakeWei[flagger]  <= stakedWei[flagger] * (1 ether - streamrConfig.slashingFraction()) / 1 ether, "error_notEnoughStake");
simplify this to just `require(committedStakeWei[flagger] <= stakedWei[flagger], "error_notEnoughStake");` unless we can figure out why we need the complexity

2023-09-08 12:55 UTC, jtakalai requested changes
I actually did request the above changes 😅

2023-09-08 13:08 UTC, samigabor commented on packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.sol
> +        // TODO: after taking at least minimumStake, all "1 - slashingFraction" here are probably overthinking
Removed

2023-09-11 13:29 UTC, jtakalai approved these changes

2023-09-12 07:32 UTC, samt1803 requested changes

2023-09-12 07:32 UTC, samt1803 commented on packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.sol
> +        require(committedStakeWei[flagger] <= stakedWei[flagger], "error_notEnoughStake");
add a test that test this edge case

2023-09-13 11:40 UTC, samigabor commented on packages/network-contracts/contracts/OperatorTokenomics/SponsorshipPolicies/VoteKickPolicy.sol
> +        require(committedStakeWei[flagger] <= stakedWei[flagger], "error_notEnoughStake");
Made require more restrictive (it now can flag up to commitedStake - slashingAmount)

2023-09-13 11:46 UTC, samigabor commented
Also changed this:
```
function minimumStakeWei() public view returns (uint) {
        return (flaggerRewardWei + flagReviewerCount * flagReviewerRewardWei) * 1 ether / slashingFraction;
    }
```
to this:
```
function minimumStakeWei() public view returns (uint) {
        return (flaggerRewardWei + flagReviewerCount * flagReviewerRewardWei) * 100 * slashingFraction / 1 ether;
    }
```

In the first case the minimumStake would decrease if the slashing increases. Probably not the desired behaviour

2023-09-13 13:28 UTC, jtakalai approved these changes

2023-09-14 09:54 UTC, merged