Operator.sol full coverage
streamr-dev/network-contracts pull request #639
Opened 2023-09-15 07:45 UTC by samigabor

2023-09-27 06:58 UTC, jtakalai requested changes

2023-09-27 06:58 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +        _setupRole(DEFAULT_ADMIN_ROLE, ownerAddress);
```suggestion
```

2023-09-27 06:58 UTC, jtakalai commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
> +            await (await operator.connect(operatorWallet).setDelegationPolicy(hardhatEthers.constants.AddressZero, 0)).wait()
```suggestion
            const operator = await deployOperatorContract(operatorWallet, {
                delegationPolicyAddress: hardhatEthers.constants.AddressZero
            })
```
and add overrides to deployOperator and deployOperatorContract

2023-09-27 13:02 UTC, samigabor commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +        _setupRole(DEFAULT_ADMIN_ROLE, ownerAddress);
Removed

2023-09-27 13:02 UTC, samigabor commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
> +            await (await operator.connect(operatorWallet).setDelegationPolicy(hardhatEthers.constants.AddressZero, 0)).wait()
Updated

2023-09-27 16:09 UTC, samigabor commented on packages/network-contracts/test/hardhat/OperatorTokenomics/deployTestContracts.ts
> +    testExchangeRatePolicy2: IExchangeRatePolicy;
Updated

2023-09-27 16:09 UTC, samigabor commented on packages/network-contracts/test/hardhat/OperatorTokenomics/deployTestContracts.ts
> +
Updated

2023-09-28 05:33 UTC, jtakalai approved these changes

2023-09-28 05:59 UTC, merged