OperatorValueUpdate fixes
streamr-dev/network-contracts pull request #696
Opened 2023-10-12 13:11 UTC by jtakalai

fix: OperatorValueUpdate should happen after withdraw

...and only once after removeSponsorship; nowadays _splitEarnings doesn't call it.

<strike>Fisherman also doesn't need to service the queue (it used to be like that before a recent change)</strike>

also lots of comments!

2023-10-13 10:07 UTC, samt1803 approved these changes

2023-10-13 10:13 UTC, samt1803 requested changes
metatx nor possible to use _msgSender inside module

2023-10-13 13:19 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/OperatorPolicies/StakeModule.sol
> +        address msgSender = _msgSender();
reverted 👍

2023-10-16 07:45 UTC, samigabor approved these changes

2023-10-16 07:57 UTC, samt1803 approved these changes

2023-10-16 07:57 UTC, merged