Add cumulativeEarningsWei to Operator and OperatorDailyBucket entities
streamr-dev/network-contracts pull request #698
Opened 2023-10-12 14:04 UTC by samigabor

2023-10-13 09:37 UTC, jtakalai approved these changes

2023-10-13 09:37 UTC, jtakalai commented on packages/network-subgraphs/src/helpers.ts
> +        bucket.cumulativeEarningsWei = operator.cumulativeEarningsWei
please move to line 153

2023-10-13 09:55 UTC, jtakalai requested changes
`cumulativeEarningsWei` should work like the other "absolute" values in the bucket

2023-10-13 09:55 UTC, jtakalai commented on packages/network-subgraphs/src/operator.ts
> +    bucket.cumulativeEarningsWei = bucket.profitsWei.plus(bucket.operatorsCutWei)
```suggestion
```

2023-10-13 09:55 UTC, jtakalai commented on packages/network-subgraphs/src/operator.ts
> +    bucket.cumulativeEarningsWei = bucket.profitsWei.plus(bucket.operatorsCutWei)
Another suggestion:
```suggestion
    bucket.cumulativeEarningsWei = operator.cumulativeEarningsWei
```
with this, maybe do the update for the other "absolute" values as well

2023-10-13 09:55 UTC, jtakalai commented on packages/network-subgraphs/src/helpers.ts
> +        bucket.cumulativeEarningsWei = operator.cumulativeEarningsWei
this should be together with absolute values

2023-10-13 09:55 UTC, jtakalai commented on packages/network-subgraphs/src/helpers.ts
> +        bucket.cumulativeEarningsWei = operator.cumulativeEarningsWei
note: delegatorCountAtStart is actually a third category: legitimately "start of bucket" type of values.

2023-10-13 12:42 UTC, samigabor commented on packages/network-subgraphs/src/helpers.ts
> +        bucket.cumulativeEarningsWei = operator.cumulativeEarningsWei
moved

2023-10-16 09:03 UTC, samt1803 approved these changes

2023-10-17 08:21 UTC, jtakalai requested changes
update comment, then good to merge 👍

2023-10-17 08:21 UTC, jtakalai commented on packages/network-subgraphs/schema.graphql
> +  "Sum of earnings today, including operator's share"
```suggestion
  "Sum of the operator's lifetime earnings (including operator's cut)"
```

2023-10-19 05:33 UTC, merged