ETH-658: Fixed early leaver penalty
streamr-dev/network-contracts pull request #704
Opened 2023-10-17 14:11 UTC by jtakalai

early leaver penalty used to depend on stake, now it's flat X DATA for everyone

add earlyLeaverPenaltyWei to StreamrConfig, use it in DefaultLeavePolicy

fixed tests, some to use real StreamrConfig values

2023-10-18 13:20 UTC, hpihkala commented
Assuming ready for review since this is not a draft PR. Requested review as Juuso might have forgotten to click that rushing to his holiday :)

2023-10-19 17:27 UTC, jtakalai commented
uh well, this was just the beginning of the PR really; since we also want unit tests... so yea more like a draft PR I guess

2023-10-20 06:25 UTC, samt1803 requested changes
some tests still fail when re-enabling all tests

2023-10-20 06:25 UTC, samt1803 commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Operator.test.ts
> +        it.only("if operator has no self-delegation, it won't get slashed for losses either", async function(): Promise<void> {
```suggestion
        it("if operator has no self-delegation, it won't get slashed for losses either", async function(): Promise<void> {
```
re-enable all tests

2023-10-20 13:32 UTC, samt1803 approved these changes

2023-10-20 13:32 UTC, merged