index event values in contracts and subgraph
streamr-dev/network-contracts pull request #725
Opened 2023-10-26 08:10 UTC by samt1803

2023-10-26 09:04 UTC, jtakalai requested changes

2023-10-26 09:04 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +    event Delegated(address indexed delegator, uint indexed amountDataWei);
amountDataWei is a "metric" argument, probably can't reasonably be indexed. Only pick addresses, enums, etc. where you can actually group things by specific values.

2023-10-26 09:05 UTC, jtakalai commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +    event Delegated(address indexed delegator, uint indexed amountDataWei);
fractions are a bit border-line okay, since we might want to filter for zero or one... but I'd maybe leave those out, too.

2023-10-26 09:13 UTC, samt1803 commented on packages/network-contracts/contracts/OperatorTokenomics/Operator.sol
> +    event Delegated(address indexed delegator, uint indexed amountDataWei);
can the filters only be "where equals" or also "where greater",.. because then amounts might again be useful if indexed?

2023-10-28 13:25 UTC, jtakalai approved these changes

2023-10-28 15:12 UTC, merged