ETH-675 Kick out a reverting mock-operator
streamr-dev/network-contracts pull request #727
Opened 2023-10-26 10:54 UTC by samigabor

2023-10-26 11:31 UTC, jtakalai requested changes

2023-10-26 11:31 UTC, jtakalai commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts
> +        await (await badOperator.unstake(sponsorship.address)).wait()
ok this is a voluntary unstake, and I guess it still would work the same way: if your transferAndCall reverts, you just lose the tokens.

But the important thing to test is: sponsorship's IKickPolicy removes the operator. That they get removed.

2023-10-26 11:31 UTC, jtakalai commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts
> +        await expect(badOperator.unstake(sponsorship.address))
you can test this more directly by asking `operator.stakedWei`

2023-10-27 07:17 UTC, samigabor commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts
> +        await (await badOperator.unstake(sponsorship.address)).wait()
Added another test where the bad operator is kicked through the admin policy

2023-10-27 07:17 UTC, samigabor commented on packages/network-contracts/test/hardhat/OperatorTokenomics/Sponsorship.test.ts
> +        await expect(badOperator.unstake(sponsorship.address))
Updated

2023-10-27 07:50 UTC, jtakalai approved these changes

2023-10-27 09:55 UTC, merged