ETH-615 Create Network subgraph entity
streamr-dev/network-contracts pull request #754
Opened 2023-11-08 11:35 UTC by samigabor

2023-11-09 12:07 UTC, samigabor commented
[Add operator.isEligibleToVote to subgraph](https://linear.app/streamr/issue/ETH-708/add-operatoriseligibletovote-to-subgraph)

2023-11-10 09:27 UTC, samt1803 commented
add totalDelegated, totalUndelegated cumulative values

2023-11-10 09:32 UTC, jtakalai requested changes

2023-11-10 09:32 UTC, jtakalai commented on packages/network-subgraphs/schema.graphql
> +  payingSponsorshipsCount: Int!
```suggestion
  "The number of all Sponsorships ever created through the SponsorshipFactory that are currently funded"
  fundedSponsorshipsCount: Int!
```

2023-11-10 09:42 UTC, samt1803 requested changes

2023-11-10 09:42 UTC, samt1803 commented on packages/network-subgraphs/src/operator.ts
> +    let operatorContract = event.address.toHexString()
remove unused values

2023-11-10 09:42 UTC, samt1803 commented on packages/network-subgraphs/src/operator.ts
> +    network.totalDelegation = network.totalDelegation.plus(newDelegation)
rename to totalDelegated or cumulativeTotalDelegated

2023-11-10 09:42 UTC, samt1803 commented on packages/network-subgraphs/src/operator.ts
> +    network.totalStake = network.totalStake.plus(stakeChange)
save() missing

2023-11-10 09:43 UTC, jtakalai requested changes
Idea: at https://github.com/streamr-dev/network-contracts/pull/754/files#diff-39b6cb2399417bc5d4d2bca0a173da5e4504765b46f60344dd8d62dd168d73d3R183 then maybe if flag result was no-kick, then copy the protection end timestamp into flag-target's Operator entity

2023-11-10 11:42 UTC, samigabor commented on packages/network-subgraphs/src/operator.ts
> +    network.totalStake = network.totalStake.plus(stakeChange)
Added

2023-11-10 11:42 UTC, samigabor commented on packages/network-subgraphs/src/operator.ts
> +    let operatorContract = event.address.toHexString()
Removed

2023-11-10 11:51 UTC, samigabor commented on packages/network-subgraphs/src/operator.ts
> +    network.totalDelegation = network.totalDelegation.plus(newDelegation)
renamed

2023-11-10 12:17 UTC, samigabor commented
> add totalDelegated, totalUndelegated cumulative values

renamed totalDelegation and added totalUndelegated

2023-11-14 09:04 UTC, jtakalai approved these changes

2023-11-14 09:59 UTC, merged