ETH-792: public permissions can't be edit/grant/delete
streamr-dev/network-contracts pull request #914
Opened 2024-10-04 15:29 UTC by jtakalai

2024-10-07 08:38 UTC, teogeb requested changes
First round of comments

2024-10-07 08:38 UTC, teogeb commented on packages/network-contracts/contracts/StreamRegistry/StreamRegistryV5.sol
> +        require(userKey != publicPermissionUserKey[streamId] || noNonPubSub, "error_publicCanOnlySubsPubl");
Maybe more straightforward:

```suggestion
        require(!(isPubSub && userKey == publicPermissionUserKey[streamId]), "error_publicCanOnlySubsPubl");
```

That way it would  be read clearly that that the combination of public permission _and_ pubsub is not allowed.

Also at line `333`.

2024-10-07 08:38 UTC, teogeb commented on packages/network-contracts/contracts/StreamRegistry/StreamRegistryV5.sol
> +        bool pubOrSub = false;
Could rename this variable to `isPubOrSub` (as that seems to be a naming convention in `network-contracts`)

2024-10-08 07:23 UTC, jtakalai commented on packages/network-contracts/contracts/StreamRegistry/StreamRegistryV5.sol
> +        bool noNonPubSub = !canEdit && !canDelete && !canGrant;
this isn't the same thing though; it can be none of those, and also not pub nor sub. The double negative is maybe confusing but also accurate.

2024-10-08 07:29 UTC, jtakalai commented on packages/network-contracts/contracts/StreamRegistry/StreamRegistryV5.sol
> +        require(userKey != publicPermissionUserKey[streamId] || noNonPubSub, "error_publicCanOnlySubsPubl");
public permission as pubsub is the allowed combination.

2024-10-08 07:49 UTC, teogeb commented on packages/network-contracts/contracts/StreamRegistry/StreamRegistryV5.sol
> +        bool noNonPubSub = !canEdit && !canDelete && !canGrant;
Hmm, very confusing indeed... How about `hasNoEditDeleteGrantPermissions`?

2024-10-10 12:21 UTC, teogeb approved these changes

2024-10-11 08:59 UTC, merged