ETH-795: Export chain-related types along with the config
streamr-dev/network-contracts pull request #923
Opened 2024-10-31 12:41 UTC by mondoreale

2024-12-02 09:47 UTC, mondoreale commented on packages/config/src/index.ts
> -export const config = {
@jtakalai thoughts?

2024-12-09 09:43 UTC, jtakalai requested changes

2024-12-09 09:43 UTC, jtakalai commented on packages/config/src/index.ts
> -export const config = {
ideally there would be a config.json that maybe then gets processed into whatever works best for a Typescript NPM package?

2025-01-27 16:48 UTC, mondoreale reviewed
@jtakalai, have a look at how it all evolved. We now have
- A single source file (config.json), and
- The generated typed version of it in `src/generated/config.ts`

The config module exports the index file which in turn exports the typed config to satisfy @harbu's `as const` request.

Additionally, the index file exports
- `Chain`,
- `ChainKey` i.e. `dev1`, `polygon`, …,
- `Config` which is the entire thing, and
- `ContractAddressKey` i.e. `DATA`, `XDATA`, `SponsorshipFactory`, and so on.

LMK your thoughts.

---

A couple of screenshots

![image](https://github.com/user-attachments/assets/e28166ae-49f6-4c72-a063-04f0afe25cc1)

![image](https://github.com/user-attachments/assets/97389185-26cd-41f2-a3be-fc40d71fb3da)

![image](https://github.com/user-attachments/assets/e5837827-0660-48a1-aa84-de4a4894398b)

2025-01-27 17:51 UTC, mondoreale commented
I seem to be unable to install per-package deps with npm v10.7… Corrupts the root package-lock.

2025-01-29 13:13 UTC, jtakalai approved these changes
very nice! 👍

2025-01-29 13:42 UTC, harbu commented on packages/config/README.md
> +
I think we should direct the user towards running `npm run build` right? My first impression reading this what that I'm required to remember to run generate-types manually before publishing when really `npm run build` would take care of it.

2025-01-29 14:42 UTC, merged